AmazonProject/Components/TypesViewComponent.cs
using System;
using System.Linq;
using AmazonProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace AmazonProject.Components
{
    public class TypesViewComponent : ViewComponent 
    {
        private IAmazonProjectRepository repo { get; set; }

        public TypesViewComponent (IAmazonProjectRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookType"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

AmazonProject/Views/Shared/BookSummary.cshtml
@{
}

@model Book

@* print off all the books in cards*@
<div class="card" style="width: 55rem;">
    <div class="card-body">
        <h5 class="card-title bg-light p-2">@Model.Title <span class="badge bg-info" style="float:right; color:white;">Price: $@Model.Price</span></h5>
        <!-- I INCLUDED THIS 'CARD-SUBTITLE' FROM BOOTSTRAP MYSELF OUTSIDE OF THE VIDEOS FOR THIS -->
        <h6 class="card-subtitle mb-2 text-muted">Author: @Model.Author</h6>

        <!-- THIS WILL PRINT OFF ALL THE INFORMATION FOR EACH BOOK-->
        <ul>
            <li>ISBN: @Model.Isbn</li>
            <li>Classification: @Model.Classification</li>
            <li>Category: @Model.Category</li>
            <li>Page Count: @Model.PageCount</li>
        </ul>

        <form method="post" asp-page="/Cart">

            <input type="hidden" asp-for="@Model.BookId"/>
            <input type="hidden" name="returnURL" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

            <span class="card-text">
                <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
            </span>
        </form> 
    </div>

</div>
<br />

AmazonProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <!--NAVIGATION BAR FROM SET UP-->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book Store Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cart" style="float:right;">View Cart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <!-- MAIN BODY SECTION THAT IS CHANGED IN EACH HTML PAGE-->
    @*<div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>*@

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            @RenderBody()
        </div>

    </div>
    <!-- FOOTER-->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AmazonProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>